### ISSUE TITLE
Video recorder

### ISSUE THREAD

**Issue by GuaiYiHu** [xiaomi-classic-dev/android_device_xiaomi_leo_old#10]
01-27 00:57:37.995   485  5773 I OMXClient: MuxOMX ctor
01-27 00:57:37.996   482  2468 I OMXMaster: makeComponentInstance(OMX.qcom.video.encoder.avc) in mediacodec process
01-27 00:57:37.997   482  2468 I OMX-VENC: Video encode perflock acquired,handle=-1
01-27 00:57:38.006   482  2468 E OMX-VENC: Setting session priority failed
01-27 00:57:38.007   482  2468 I OMX-VENC: Component_init : OMX.qcom.video.encoder.avc : return = 0x0
01-27 00:57:38.008   485  5772 I MediaCodec: MediaCodec will operate in async mode
01-27 00:57:38.008   482   525 E OMX-VENC: Failed setting color format 7fa30c04
01-27 00:57:38.008   482   525 E OMX-VENC: ERROR: venc_set_param input failed
01-27 00:57:38.008   482   525 E OMXNodeInstance: setParameter(1e20041:qcom.encoder.avc, OMX.google.android.index.storeMetaDataInBuffers(0x7f00001c): Input:0 en=1 type=3) ERROR: UnsupportedSetting(0x80001019)
01-27 00:57:38.009   485  5773 E ACodec  : [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (input) failed w/ err -1010
01-27 00:57:38.009   485  5773 E ACodec  : [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
01-27 00:57:38.009   485  5773 E ACodec  : signalError(omxError 0xfffffc0e, internalError -1010)
01-27 00:57:38.009   485  5772 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
01-27 00:57:38.009   485   485 E MediaCodec: configure failed with err 0xfffffc0e, resetting...
01-27 00:57:38.010   482   482 I OMX-VENC: Component Deinit
01-27 00:57:38.010   482   482 I OMX-VENC: Video encode perflock released
01-27 00:57:38.012   485  5773 I MediaPlayerService: MediaPlayerService::getOMX
01-27 00:57:38.012   485  5773 I OMXClient: MuxOMX ctor
01-27 00:57:38.013   482  2669 I OMXMaster: makeComponentInstance(OMX.qcom.video.encoder.avc) in mediacodec process
01-27 00:57:38.014   482  2669 I OMX-VENC: Video encode perflock acquired,handle=-1
01-27 00:57:38.015   482  2669 E OMX-VENC: Setting session priority failed
01-27 00:57:38.016   482  2669 I OMX-VENC: Component_init : OMX.qcom.video.encoder.avc : return = 0x0
01-27 00:57:38.018   482   525 I OMX-VENC: Component Deinit
01-27 00:57:38.018   482   525 I OMX-VENC: Video encode perflock released
01-27 00:57:38.019   485  5781 I MediaPlayerService: MediaPlayerService::getOMX
01-27 00:57:38.020   485  5781 I OMXClient: MuxOMX ctor
01-27 00:57:38.021   482  2468 I OMXMaster: makeComponentInstance(OMX.google.h264.encoder) in mediacodec process
01-27 00:57:38.023   485  5772 I MediaCodec: MediaCodec will operate in async mode
01-27 00:57:38.025   485  5781 I ACodec  : setupAVCEncoderParameters with [profile: Baseline] [level: Level41]
01-27 00:57:38.025   485  5781 I ACodec  : [OMX.google.h264.encoder] cannot encode color aspects. Ignoring.
01-27 00:57:38.026   485  5781 I ACodec  : [OMX.google.h264.encoder] cannot encode HDR static metadata. Ignoring.
01-27 00:57:38.026   485  5781 I ACodec  : setupVideoEncoder succeeded
01-27 00:57:38.026   482  2468 E OMXNodeInstance: setConfig(1e20043:google.h264.encoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001001)
01-27 00:57:38.026   485  5781 I ACodec  : codec does not support config priority (err -2147483648)
01-27 00:57:38.030   482   482 E SimpleSoftOMXComponent: b/63522430, Buffer size is too small.
01-27 00:57:38.031   482   482 E OMXNodeInstance: useBuffer(1e20043:google.h264.encoder, Input:0 8@0xf6690148) ERROR: BadParameter(0x80001005)
01-27 00:57:38.031   485  5781 E ACodec  : Failed to allocate buffers after transitioning to IDLE state (error 0x80000000)
01-27 00:57:38.031   485  5781 E ACodec  : signalError(omxError 0x80001001, internalError -2147483648)
01-27 00:57:38.031   485  5772 E MediaCodec: Codec reported err 0x80001001, actionCode 0, while in state 5
01-27 00:57:38.031   482  2468 W OMXNodeInstance: [1e20043:google.h264.encoder] Attempt to remove an active buffer [0] we know nothing about...
01-27 00:57:38.031   482  2468 E OMXNodeInstance: b/25884056 1398
01-27 00:57:38.032   485  5781 W AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
01-27 00:57:38.032   485  5781 W AHierarchicalStateMachine:   int32_t type = 0
01-27 00:57:38.032   485  5781 W AHierarchicalStateMachine:   int32_t event = 0
01-27 00:57:38.032   485  5781 W AHierarchicalStateMachine:   int32_t data1 = 0
01-27 00:57:38.032   485  5781 W AHierarchicalStateMachine:   int32_t data2 = 1
01-27 00:57:38.032   485  5781 W AHierarchicalStateMachine: } unhandled in root state.
01-27 00:57:38.035   485   485 E StagefrightRecorder: Failed to create video encoder
01-27 00:57:38.035   485   485 D CameraSource: reset: E
01-27 00:57:38.035   478   478 W CameraClient: attempt to use a locked camera from a different process (old pid 485, new pid 5412)
01-27 00:57:38.036   485   485 D CameraSource: reset: X
01-27 00:57:38.036  5412  5412 E MediaRecorder: start failed: -2147483648

**Comment by GuaiYiHu** [comment]
On oreo
https://github.com/halogenOS/android_frameworks_av/commit/57bba830731b4b24845aaafd7e3686c83aad1391

**Comment by Saideepakraju** [comment]
how to solve this issue?
Iam facing the same issue.
Thanks in Advance.

**Comment by GuaiYiHu** [comment]
Drop this.
https://github.com/Demon000/kernel_xiaomi_msm8992/commit/f8f73cbd58ed44404e784af84da99580f86fcfea

**Comment by Saideepakraju** [comment]
Iam using this OMX.google.h264.encoder encoder.
Iam getting this error,


05-07 09:40:30.212   241  1723 I ACodec  : setupVideoEncoder succeeded
05-07 09:40:30.212   245  1478 E OMXNodeInstance: setConfig(0xae1bd600:google.h264.encoder, ConfigPriority(0x6f800002)) ERROR: Undefined(0x80001)
05-07 09:40:30.212   241  1723 I ACodec  : codec does not support config priority (err -2147483648)
**05-07 09:40:30.212   245  1478 E OMXNodeInstance: getConfig(0xae1bd600:google.h264.encoder, ConfigLatency(0x6f800005)) ERROR: Undefined(0x800010)
05-07 09:40:30.212   245  1478 E OMXNodeInstance: getConfig(0xae1bd600:google.h264.encoder, ConfigAndroidVendorExtension(0x6f100004)) ERROR: Und)
05-07 09:40:30.215   184   184 W /system/bin/hw/android.hidl.allocator@1.0-service: ashmem_create_region(8) returning hidl_memory(0xac7977d0, 8)
05-07 09:40:30.215   245  1478 E SimpleSoftOMXComponent: b/63522430, Buffer size is too small.
05-07 09:40:30.215   245  1478 E OMXNodeInstance: useBuffer(0xae1bd600:google.h264.encoder, Input:0 8@0xae415090) ERROR: BadParameter(0x80001005)
05-07 09:40:30.215   241  1723 E ACodec  : Failed to allocate buffers after transitioning to IDLE state (error 0xffffffea)
05-07 09:40:30.215   241  1723 E ACodec  : signalError(omxError 0x80001001, internalError -22)**
05-07 09:40:30.215   241  1722 E MediaCodec: Codec reported err 0xffffffea, actionCode 0, while in state 5
05-07 09:40:30.216   245  1478 W OMXNodeInstance: [0xae1bd600:google.h264.encoder] Attempt to remove an active buffer [0] we know nothing about..
05-07 09:40:30.216   245  1478 E OMXNodeInstance: b/25884056
05-07 09:40:30.216   241  1723 W AHierarchicalStateMachine: Warning message AMessage(what = 'omxI') = {
05-07 09:40:30.216   241  1723 W AHierarchicalStateMachine:   int32_t type = 0
05-07 09:40:30.216   241  1723 W AHierarchicalStateMachine:   int32_t event = 0
05-07 09:40:30.216   241  1723 W AHierarchicalStateMachine:   int32_t data1 = 0
05-07 09:40:30.216   241  1723 W AHierarchicalStateMachine:   int32_t data2 = 1
05-07 09:40:30.216   241  1723 W AHierarchicalStateMachine: } unhandled in root state.
05-07 09:40:30.217   241   241 E StagefrightRecorder: Failed to create video encoder
05-07 09:40:30.218   241   241 D CameraSource: reset: E
05-07 09:40:30.218   232  1627 W CameraClient: attempt to use a locked camera from a different process (old pid 241, new pid 1330)
05-07 09:40:30.218   241   241 D CameraSource: reset: X
05-07 09:40:30.218  1330  1330 E MediaRecorder: start failed: -2147483648
05-07 09:40:30.218  1330  1330 E Preview : runtime exception starting video recorder

**Comment by GuaiYiHu** [comment]
Fixed

**Comment by Saideepakraju** [comment]
Not yet solved
