### ISSUE TITLE
Accelerometer doesn't work

### ISSUE THREAD

**Issue by etnperlong** [xiaomi-classic-dev/android_device_xiaomi_leo_old#6]
Accelerometer doesn't work when I check it in Sensor MultiTool, could you please fix it, thank you!
通过传感器检测工具查看，发现加速度传感器无法工作。请问会修复么？感谢！

[![295670624825630102.jpg](https://i.loli.net/2017/12/30/5a478a2f6ba4f.jpg)](https://i.loli.net/2017/12/30/5a478a2f6ba4f.jpg)

**Comment by GuaiYiHu** [comment]
Works fine for me. Igonerd. :p 

![screenshot_20180106-230932](https://user-images.githubusercontent.com/17136448/34640930-012049cc-f337-11e7-836e-9a11132d1401.png)

**Comment by etnperlong** [comment]
well, now I can't reproduce this problem :D


2018年1月6日 23:13，"乖奕虎" <notifications@github.com>写道：
